# Generated by Django 3.2.3 on 2021-07-14 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fishfarm', '0008_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('quan', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.AddField(
            model_name='orderel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishfarm.req'),
        ),
    ]
