# Generated by Django 3.2.3 on 2021-07-17 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishfarm', '0009_auto_20210715_0051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
